<template>
  <div
    class="table-node"
    :style="{ width: nodeWidth + 'px' }"
  >
    <div class="node-header">
      <div class="table-info">
        <span class="resize-indicator nodrag" @mousedown="startHeaderResize">⋮⋮</span>
        <span class="table-name">{{ data.table }}</span>
        <span v-if="computedAlias" class="table-alias" :title="`Alias: ${computedAlias}`">
          ({{ computedAlias }})
        </span>
      </div>
      <button class="close-button nodrag" @click.stop="removeNode" title="Remove table">
        ✕
      </button>
    </div>

    <div class="node-body">
      <div
        v-for="(column, index) in data.columns"
        :key="column.name"
        class="column-row"
      >
        <!-- Target handle (left side) - visible dot -->
        <Handle
          :id="`${data.table}-${column.name}-target`"
          type="target"
          :position="Position.Left"
          class="column-handle column-handle-target"
        />

        <!-- Checkbox for column selection -->
        <n-checkbox
          v-model:checked="selectedColumnsMap[column.name]"
          class="column-checkbox"
        >
          <div class="column-content">
            <span class="column-name-text">{{ column.name }}</span>
            <span class="column-type-text">{{ column.type }}</span>
          </div>
        </n-checkbox>

        <!-- Source handle (right side) - visible dot -->
        <Handle
          :id="`${data.table}-${column.name}-source`"
          type="source"
          :position="Position.Right"
          class="column-handle column-handle-source"
        />
      </div>
    </div>

    <!-- Resize handle - corner -->
    <div
      class="resize-handle nodrag"
      @mousedown.stop="startResize"
      title="Drag to resize width"
    >
      <svg width="12" height="12" viewBox="0 0 12 12" fill="currentColor">
        <path d="M11 11L11 7M11 11L7 11M11 11L6 6M11 3L11 1L9 1M3 11L1 11L1 9" stroke="currentColor" stroke-width="1.5" fill="none" stroke-linecap="round"/>
      </svg>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, watch, computed } from 'vue'
import { Handle, Position } from '@vue-flow/core'
import { useCraftStore } from '@/store/craftStore'

const props = defineProps({
  data: {
    type: Object,
    required: true
  },
  id: {
    type: String,
    required: false
  }
})

const craftStore = useCraftStore()

// Create a map for selected columns (checkbox state)
const selectedColumnsMap = reactive({})

// Node width for resizing
const nodeWidth = ref(props.data.width || 280)

// Initialize selected columns map
if (props.data.selectedColumns) {
  props.data.selectedColumns.forEach(col => {
    selectedColumnsMap[col] = true
  })
}

// Use alias from node data (generated by store)
const computedAlias = computed(() => {
  return props.data.alias || props.data.table
})

// Watch for changes and update store
watch(selectedColumnsMap, (newMap) => {
  const selectedCols = Object.keys(newMap).filter(key => newMap[key])
  const nodeIndex = craftStore.nodes.findIndex(n => n.data?.table === props.data.table)
  if (nodeIndex !== -1) {
    craftStore.nodes[nodeIndex].data.selectedColumns = selectedCols
  }
}, { deep: true })

const removeNode = () => {
  const node = craftStore.nodes.find(n => n.data?.table === props.data.table)
  if (node) {
    craftStore.removeNode(node.id)
  }
}

// Resize functionality - from corner handle
const startResize = (event) => {
  event.preventDefault()
  event.stopPropagation()

  const startX = event.clientX
  const startWidth = nodeWidth.value
  let rafId = null

  const onMouseMove = (e) => {
    if (rafId) cancelAnimationFrame(rafId)

    rafId = requestAnimationFrame(() => {
      const deltaX = e.clientX - startX
      const newWidth = Math.max(240, Math.min(600, startWidth + deltaX))
      nodeWidth.value = newWidth
    })
  }

  const onMouseUp = () => {
    if (rafId) cancelAnimationFrame(rafId)

    document.removeEventListener('mousemove', onMouseMove)
    document.removeEventListener('mouseup', onMouseUp)
    document.body.style.cursor = ''
    document.body.style.userSelect = ''

    // Only update store once when done
    const nodeIndex = craftStore.nodes.findIndex(n => n.data?.table === props.data.table)
    if (nodeIndex !== -1) {
      craftStore.nodes[nodeIndex].data.width = nodeWidth.value
    }
  }

  document.addEventListener('mousemove', onMouseMove)
  document.addEventListener('mouseup', onMouseUp)
  document.body.style.cursor = 'ew-resize'
  document.body.style.userSelect = 'none'
}

// Resize functionality - from header (horizontal resize)
const startHeaderResize = (event) => {
  // Don't resize if clicking close button
  const target = event.target
  if (target.classList.contains('close-button') || target.closest('.close-button')) {
    return
  }

  // Only resize if clicking on the resize indicator
  if (!target.classList.contains('resize-indicator') &&
      !target.closest('.resize-indicator')) {
    return
  }

  event.preventDefault()
  event.stopPropagation()

  const startX = event.clientX
  const startWidth = nodeWidth.value
  let rafId = null

  const onMouseMove = (e) => {
    if (rafId) cancelAnimationFrame(rafId)

    rafId = requestAnimationFrame(() => {
      const deltaX = e.clientX - startX
      const newWidth = Math.max(240, Math.min(600, startWidth + deltaX))
      nodeWidth.value = newWidth
    })
  }

  const onMouseUp = () => {
    if (rafId) cancelAnimationFrame(rafId)

    document.removeEventListener('mousemove', onMouseMove)
    document.removeEventListener('mouseup', onMouseUp)
    document.body.style.cursor = ''
    document.body.style.userSelect = ''

    // Only update store once when done
    const nodeIndex = craftStore.nodes.findIndex(n => n.data?.table === props.data.table)
    if (nodeIndex !== -1) {
      craftStore.nodes[nodeIndex].data.width = nodeWidth.value
    }
  }

  document.addEventListener('mousemove', onMouseMove)
  document.addEventListener('mouseup', onMouseUp)
  document.body.style.cursor = 'ew-resize'
  document.body.style.userSelect = 'none'
}
</script>

<style scoped>
.table-node {
  background: #1a1f2e;
  border: 2px solid #63e2b7;
  border-radius: 8px;
  min-width: 240px;
  box-shadow: 0 4px 12px rgba(99, 226, 183, 0.2);
  position: relative;
  overflow: hidden;
}

/* Visual guide for connection points */
.table-node::before,
.table-node::after {
  content: '';
  position: absolute;
  top: 50%;
  transform: translateY(-50%);
  width: 8px;
  height: 40%;
  background: linear-gradient(
    to bottom,
    transparent,
    rgba(99, 226, 183, 0.2),
    transparent
  );
  pointer-events: none;
}

.table-node::before {
  left: -4px;
  border-radius: 4px 0 0 4px;
}

.table-node::after {
  right: -4px;
  border-radius: 0 4px 4px 0;
}

.node-header {
  background: #63e2b7;
  color: #0f1419;
  padding: 10px;
  font-weight: 600;
  display: flex;
  justify-content: space-between;
  align-items: center;
  border-radius: 6px 6px 0 0;
  user-select: none;
}

.resize-indicator {
  cursor: ew-resize;
  font-size: 1rem;
  padding: 0 8px 0 4px;
  margin-left: -4px;
  color: rgba(15, 20, 25, 0.4);
  transition: all 0.2s;
  letter-spacing: -2px;
  font-weight: bold;
}

.resize-indicator:hover {
  color: rgba(15, 20, 25, 0.7);
  transform: scaleX(1.2);
}

.table-info {
  display: flex;
  align-items: center;
  gap: 6px;
  flex: 1;
}

.table-name {
  font-size: 0.95rem;
  font-weight: 600;
}

.table-alias {
  font-size: 0.8rem;
  font-weight: 500;
  opacity: 0.8;
  font-family: monospace;
  background: rgba(15, 20, 25, 0.2);
  padding: 2px 6px;
  border-radius: 3px;
}

.close-button {
  background: rgba(15, 20, 25, 0.3);
  border: 1px solid rgba(15, 20, 25, 0.5);
  color: #0f1419;
  width: 22px;
  height: 22px;
  border-radius: 50%;
  cursor: pointer;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 1rem;
  font-weight: bold;
  transition: all 0.2s;
  padding: 0;
  line-height: 1;
}

.close-button:hover {
  background: #ff4757;
  color: #fff;
  border-color: #ff4757;
  transform: scale(1.1);
}

.close-button:active {
  transform: scale(0.95);
}

.node-body {
  padding: 10px;
  max-height: none;
  overflow: visible;
  position: relative;
}

.node-body::-webkit-scrollbar {
  width: 6px;
  height: 6px;
}

.node-body::-webkit-scrollbar-track {
  background: rgba(99, 226, 183, 0.1);
  border-radius: 3px;
}

.node-body::-webkit-scrollbar-thumb {
  background: #63e2b7;
  border-radius: 3px;
}

.node-body::-webkit-scrollbar-thumb:hover {
  background: #4dd09a;
}

.column-row {
  padding: 6px 20px;
  color: #fff;
  font-size: 0.85rem;
  position: relative;
  display: flex;
  align-items: center;
  gap: 8px;
  border-bottom: 1px solid rgba(99, 226, 183, 0.1);
  transition: background 0.2s;
  min-width: fit-content;
}

.column-row:hover {
  background: rgba(99, 226, 183, 0.05);
}

.column-row:last-child {
  border-bottom: none;
}

.column-checkbox {
  flex: 1;
}

.column-content {
  display: flex;
  align-items: center;
  gap: 8px;
  width: 100%;
  min-width: 0;
}

.column-name-text {
  color: #fff;
  font-weight: 500;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  flex: 1;
  min-width: 0;
}

.column-name-text:hover {
  overflow: visible;
  white-space: normal;
  word-break: break-all;
}

.column-type-text {
  color: #8896a8;
  font-size: 0.7rem;
  font-style: italic;
  flex-shrink: 0;
  margin-left: auto;
}

:deep(.n-checkbox__label) {
  color: #fff;
  width: 100%;
}

/* Column handles - ALWAYS VISIBLE */
.column-handle {
  width: 12px !important;
  height: 12px !important;
  background: #63e2b7 !important;
  border: 2px solid #0f1419 !important;
  border-radius: 50% !important;
  position: absolute !important;
  cursor: crosshair !important;
  z-index: 10 !important;
  transition: all 0.2s;
}

.column-handle:hover {
  background: #4dd09a !important;
  transform: scale(1.4);
  box-shadow: 0 0 8px rgba(99, 226, 183, 0.6);
}

.column-handle-source {
  right: 0px !important;
}

.column-handle-target {
  left: 0px !important;
}

/* Connection line styling */
.column-handle.connecting {
  background: #ffd700 !important;
  transform: scale(1.5);
  box-shadow: 0 0 12px rgba(255, 215, 0, 0.8);
}

/* Resize handle */
.resize-handle {
  position: absolute;
  bottom: 0;
  right: 0;
  width: 24px;
  height: 24px;
  cursor: nwse-resize;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #63e2b7;
  font-size: 1rem;
  opacity: 0.5;
  transition: all 0.2s;
  user-select: none;
  z-index: 100;
  background: linear-gradient(135deg, transparent 50%, rgba(99, 226, 183, 0.15) 50%);
  border-bottom-right-radius: 6px;
}

.resize-handle:hover {
  opacity: 1;
  background: linear-gradient(135deg, transparent 50%, rgba(99, 226, 183, 0.35) 50%);
  transform: scale(1.1);
}

.resize-handle svg {
  width: 14px;
  height: 14px;
  opacity: 0.8;
}

.table-node:hover .resize-handle {
  opacity: 0.8;
}
</style>
